apiVersion: v1
kind: page
spec:
  id: kfLTB1F
  title: page1
  content:
    - component: PageRow
      name: pageRow6
      children:
        - component: TextField
          name: searchBookByTitle
          props:
            label: Search Book By Title
            fullWidth: true
    - component: PageRow
      name: pageRow11
      children:
        - component: codeComponent.CustomList
          name: ListComponent
          props:
            text:
              $$jsExpression: |
                searchBookByTitle.value
            dataList:
              $$jsExpression: |
                getBooks.data
  queries:
    - name: getBooks
      query:
        kind: rest
        url: http://localhost:3030/books
        headers: []
        method: GET
  display: shell
