apiVersion: v1
kind: page
spec:
  id: U39SV-9
  title: Default page
  display: standalone
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: Tabs
          name: tabs
          props:
            tabs:
              - title: Books
                name: books
              - title: Add Book
                name: add-book
              - title: Tab three
                name: tab-three
          layout:
            horizontalAlign: start
    - component: PageRow
      name: pageRow7
      children:
        - component: Container
          name: container1
          children:
            - component: PageRow
              name: pageRow8
              children:
                - component: PageColumn
                  name: pageColumn3
                  layout:
                    columnSize: 1
                  children:
                    - component: Text
                      name: text
                      layout:
                        horizontalAlign: center
                      props:
                        value: Publish Your Book
                        variant: h1
                        mode: text
                        sx:
                          textAlign: center
                          color: blue
                          fontSize: 40px
                          marginBottom: 20px
                    - component: Container
                      name: container
                      children:
                        - component: PageRow
                          name: pageRow3
                          children:
                            - component: Form
                              name: form
                              layout:
                                columnSize: 1
                              props:
                                hasResetButton: true
                                formControlsAlign: end
                              children:
                                - component: PageRow
                                  name: pageRow4
                                  children:
                                    - component: PageColumn
                                      name: pageColumn1
                                      layout:
                                        columnSize: 1
                                      children:
                                        - component: PageRow
                                          name: pageRow5
                                          props:
                                            justifyContent: start
                                          children:
                                            - component: PageColumn
                                              name: pageColumn
                                              layout:
                                                columnSize: 1
                                              children:
                                                - component: TextField
                                                  name: authorField
                                                  props:
                                                    label: Author Name
                                                    isRequired: true
                                                    isInvalid:
                                                      $$jsExpression: >
                                                        // authorField.value

                                                        new RegExp(/[^a-zA-Z0-9 ]/g).test(authorField.value)
                                                    fullWidth: true
                                                    minLength: 5
                                                - component: TextField
                                                  name: bookCoverImg
                                                  props:
                                                    label: Book Cover Img Link
                                                    fullWidth: true
                                                    isRequired: true
                                                - component: TextField
                                                  name: ebookLink
                                                  props:
                                                    label: E-Book Link
                                                    minLength: -4
                                                    fullWidth: true
                                                - component: TextField
                                                  name: title
                                                  props:
                                                    isRequired: true
                                                    isInvalid:
                                                      $$jsExpression: >
                                                        // authorField.value

                                                        new RegExp(/[^a-zA-Z0-9 ]/g).test(title.value)
                                                    minLength: 5
                                                    fullWidth: true
                                                    label: Title
                                            - component: PageColumn
                                              name: pageColumn2
                                              layout:
                                                columnSize: 1
                                              children:
                                                - component: Select
                                                  name: country
                                                  layout:
                                                    horizontalAlign: center
                                                  props:
                                                    isRequired: true
                                                    fullWidth: true
                                                    label: Country
                                                    options:
                                                      - Australia
                                                      - Austria
                                                      - Bahrain
                                                      - Belgium
                                                      - UK
                                                      - India
                                                - component: Select
                                                  name: language
                                                  props:
                                                    options:
                                                      - Hindi
                                                      - English
                                                      - Gujarati
                                                    label: Language
                                                    fullWidth: true
                                                    isRequired: true
                                                - component: TextField
                                                  name: page
                                                  props:
                                                    label: page
                                                    isRequired: true
                                                    minLength: 3
                                                    isInvalid:
                                                      $$jsExpression: >
                                                        // authorField.value

                                                        new RegExp(/[^0-9]/g).test(page.value)
                                                    fullWidth: true
                                                - component: DatePicker
                                                  name: year
                                                  props:
                                                    isRequired: true
                                                    name: Year
                                                    fullWidth: true
                                                    format:
                                                      $$jsExpression: |
                                                        "YYYY"
          props:
            sx:
              $$jsExpression: >
                tabs.value == "add-book" ? { display: "block" } : { display:
                "none" }
    - component: PageRow
      name: pageRow1
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                bookList.data
            columns:
              - field: author
                type: string
              - field: country
                type: string
              - field: imageLink
                type: string
              - field: language
                type: string
              - field: link
                type: link
              - field: pages
                type: number
              - field: title
                type: string
              - field: year
                type: number
            sx:
              $$jsExpression: >
                tabs.value == "books" ? { display: "block" } : { display: "none"
                }
  queries:
    - name: bookList
      query:
        kind: rest
        url: http://localhost:3030/books
        headers: []
        method: GET
